#!/bin/sh
# install_pre_commit.sh — Linux/macOS 装 git pre-commit hook
# 用法: 在仓库根跑  sh scripts/install_pre_commit.sh
#
# 装当前仓库的 hook(自动从脚本位置推断 repo root),拦 ticker/公司名 mismatch。
# 与 install_pre_commit.ps1 等价(Linux 版)。

set -e

# 从脚本所在路径推断 repo root(脚本位于 <repo>/scripts/install_pre_commit.sh)
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
HOOK_DIR="$REPO/.git/hooks"

if [ ! -d "$HOOK_DIR" ]; then
  echo "Skip: $REPO - no .git/hooks dir (not a git repo?)"
  exit 1
fi

HOOK_PATH="$HOOK_DIR/pre-commit"
VERIFY_REL="scripts/verify_tickers.py"  # 相对 repo root

# 注意:EODHD_API_KEY 必须在 user shell env 里自己 export,不硬编码在 hook
# (.git/hooks/ 不被 git tracked,但 install 脚本本身被 tracked,key 不能进源码)
cat > "$HOOK_PATH" <<EOF
#!/bin/sh
# Auto-generated by install_pre_commit.sh on $(date -u +%Y-%m-%d)
# 拦截 ticker / 公司名 mismatch — L1+L2+L3 防御
# REQUIRES: EODHD_API_KEY env var (用户自行 export 在 ~/.bashrc / ~/.zshrc)
if [ -z "\$EODHD_API_KEY" ]; then
    echo "[pre-commit] WARN: EODHD_API_KEY not set — verify 将只用 cached ticker_truth.csv(无法验证新增 ticker)"
fi
cd "$REPO" && python "$VERIFY_REL" --staged
exit \$?
EOF

chmod +x "$HOOK_PATH"

echo "Installed: $HOOK_PATH -> $REPO/$VERIFY_REL"
echo ""
echo "完成。下次 git commit 前会自动 scan staged 文件 ticker mismatch。"
echo "bypass(仅紧急): git commit --no-verify"
